<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_TestAccountKaryawan1_c-avatar-img</name>
   <tag></tag>
   <elementGuidId>561ee766-4a44-4ce6-91df-b77f1958fad9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/header/ul[3]/li/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.c-header-nav-link.nav-link > div.c-avatar > img.c-avatar-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Sign Out&quot;i >> internal:label=&quot;Dropdown toggle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>93016ae7-7fcd-4313-853c-e06aac9380c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-avatar-img</value>
      <webElementGuid>6f5d85b1-7888-4fad-b2e3-291d0a7a62fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://103.180.125.58:11000/media/uploads/images/img_61b1a6bb45_profil user.png</value>
      <webElementGuid>fcd126ad-1fac-4bf8-84c9-871f0447cf73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>admin@bootstrapmaster.com</value>
      <webElementGuid>68809534-3ef2-461e-911d-abde40880c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout&quot;]/div[@class=&quot;c-wrapper&quot;]/header[@class=&quot;header-root c-header c-header-light c-header-fixed&quot;]/ul[@class=&quot;px-3 c-header-nav&quot;]/li[@class=&quot;c-header-nav-items mx-2 dropdown nav-item&quot;]/a[@class=&quot;c-header-nav-link nav-link&quot;]/div[@class=&quot;c-avatar&quot;]/img[@class=&quot;c-avatar-img&quot;]</value>
      <webElementGuid>6017bfe3-152c-4034-9969-4521c01e6c12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/header/ul[3]/li/a/div/img</value>
      <webElementGuid>424cbd17-848b-4999-85fe-f48b96d8b361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='admin@bootstrapmaster.com'])[2]</value>
      <webElementGuid>fb8fead4-185f-4b11-9b45-bac2d3e205cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>376c1066-5902-4afd-ade5-e6fc3c5808bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://103.180.125.58:11000/media/uploads/images/img_61b1a6bb45_profil user.png' and @alt = 'admin@bootstrapmaster.com']</value>
      <webElementGuid>fffada47-63f4-4ae0-a798-108a9802eb28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
