<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--AdminyanragaTris Retno Ary_9c4777</name>
   <tag></tag>
   <elementGuidId>2bc64e4b-c79e-4ddc-837b-a15d1152fe72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='id_pic']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;id_pic&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;id_pic&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6e0afcf5-af07-4c50-9589-c11b36d0bc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1f134414-4cbd-42a8-be77-c6dcca9187f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>58549cd1-ce47-4ee0-a70f-b330a91e44f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_pic</value>
      <webElementGuid>c8428d43-9fc7-42c4-b60c-d47c59dbd8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AdminyanragaTris Retno AryaniTris R ATestingDemoAppTesting123Testing Karyawan Baru scTestDev1TestAccountPM1test uat2Test UAT test nama lengkapTest Karyawan BaruSUHERMAN RIYANTOSanti Dwi Astuti123RonaldoRatnaRamdanProject Managet TestProject Manager PrimaMikala FazaMika AnasMentari muliaMentari muliaMentari muliaLovensia Zukruff AlbasitJohn Data AnalystIka AnasherviHaeranierina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiabzBAMBANG ARIFINasdAndriAhlan RezkiAgus Setyaadnan111</value>
      <webElementGuid>56d10c26-9d35-49cd-ac56-9256b9debe24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout&quot;]/div[@class=&quot;c-wrapper&quot;]/div[@class=&quot;c-body&quot;]/main[@class=&quot;c-main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;fade show&quot;]/div[@class=&quot;container-mains&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;mb-4 card-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row form-group my-0 mx-2&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>ffafab24-78bf-4973-8405-ec1066f70c04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='id_pic']</value>
      <webElementGuid>3eaadbff-79d3-45cd-b34c-2ad021179cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div/div/div[2]/div[3]/div[2]/div/select</value>
      <webElementGuid>e01848af-f764-41e2-8d07-94da6f72aa2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama PIC'])[1]/following::select[1]</value>
      <webElementGuid>17915edc-c09d-4763-87c1-695ae410a54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Lembur'])[1]/following::select[2]</value>
      <webElementGuid>a9849f3c-6b7f-47d8-87e5-fa76f64abc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan Lembur'])[1]/preceding::select[1]</value>
      <webElementGuid>ca318be3-a2a4-42f9-a93c-559192f05aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanda Tangan Digital'])[1]/preceding::select[1]</value>
      <webElementGuid>3d18335c-4a2b-4d10-809e-625e96886bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>52d7dd45-5231-4666-a102-2cfa5ec85696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = '-Select-' and @name = 'id_pic' and (text() = '--Select--AdminyanragaTris Retno AryaniTris R ATestingDemoAppTesting123Testing Karyawan Baru scTestDev1TestAccountPM1test uat2Test UAT test nama lengkapTest Karyawan BaruSUHERMAN RIYANTOSanti Dwi Astuti123RonaldoRatnaRamdanProject Managet TestProject Manager PrimaMikala FazaMika AnasMentari muliaMentari muliaMentari muliaLovensia Zukruff AlbasitJohn Data AnalystIka AnasherviHaeranierina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiabzBAMBANG ARIFINasdAndriAhlan RezkiAgus Setyaadnan111' or . = '--Select--AdminyanragaTris Retno AryaniTris R ATestingDemoAppTesting123Testing Karyawan Baru scTestDev1TestAccountPM1test uat2Test UAT test nama lengkapTest Karyawan BaruSUHERMAN RIYANTOSanti Dwi Astuti123RonaldoRatnaRamdanProject Managet TestProject Manager PrimaMikala FazaMika AnasMentari muliaMentari muliaMentari muliaLovensia Zukruff AlbasitJohn Data AnalystIka AnasherviHaeranierina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiabzBAMBANG ARIFINasdAndriAhlan RezkiAgus Setyaadnan111')]</value>
      <webElementGuid>3b1b8bbe-4634-4a5e-8364-7ba5c20217a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
