<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-Select-yanragaTris Retno AryaniTris_df0b57</name>
   <tag></tag>
   <elementGuidId>351c7a62-0a9e-4277-8725-0272f38e6531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='id_pic']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;id_pic&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;id_pic&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>61bfc8da-069f-4f23-b570-fa249adf0c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9cf63cfa-a764-4f88-bb3b-6fc8e01ccd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>b1d17520-304e-480d-828e-1f1c06960c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_pic</value>
      <webElementGuid>d38f6050-0ab4-400b-a1e2-71817a12a7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Select-yanragaTris Retno AryaniTris R ATestingDemoAppTesting123Testing Karyawan Baru scTestDev1TestAccountPM1test uat2Test UAT test nama lengkapTest Karyawan BaruSUHERMAN RIYANTOSanti Dwi Astuti123RonaldoRatnaRamdanProject Managet TestProject Manager PrimaMikala FazaMika AnasMentari muliaMentari muliaMentari muliaLovensia Zukruff AlbasitJohn Data AnalystIka AnasherviHaeranierina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiabzBAMBANG ARIFINasdAndriAhlan RezkiAgus Setyaadnan111</value>
      <webElementGuid>6e27d02e-190f-4810-87f9-315ee0d7b6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout&quot;]/div[@class=&quot;c-wrapper&quot;]/div[@class=&quot;c-body&quot;]/main[@class=&quot;c-main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;fade show&quot;]/div[@class=&quot;container-mains&quot;]/div[@class=&quot;justify-content-center row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;mb-4 card-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row form-group my-0 mx-2&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>ef6eb24c-e2a0-45f2-9063-846c00728f53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='id_pic']</value>
      <webElementGuid>143ad086-ae2d-476b-b307-e8ddccb13109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div/div/div/div/div[2]/div[2]/div[2]/div/select</value>
      <webElementGuid>4dd89159-4937-4958-ad21-f9d250a4cf95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama PIC'])[1]/following::select[1]</value>
      <webElementGuid>5fd757dc-b4af-4081-87f1-84056ee132b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Cuti'])[1]/following::select[2]</value>
      <webElementGuid>8e3f97f8-82de-44c4-8aed-075ea8c01c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan Cuti'])[1]/preceding::select[1]</value>
      <webElementGuid>aa0229f2-73c7-421f-a8b8-b0edd50172b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanda Tangan Digital'])[1]/preceding::select[1]</value>
      <webElementGuid>6c994de4-9634-4f3c-b13b-55a39bc3860b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>ac392da9-7835-44d3-8f22-61bc5cd48f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = '-Select-' and @name = 'id_pic' and (text() = '-Select-yanragaTris Retno AryaniTris R ATestingDemoAppTesting123Testing Karyawan Baru scTestDev1TestAccountPM1test uat2Test UAT test nama lengkapTest Karyawan BaruSUHERMAN RIYANTOSanti Dwi Astuti123RonaldoRatnaRamdanProject Managet TestProject Manager PrimaMikala FazaMika AnasMentari muliaMentari muliaMentari muliaLovensia Zukruff AlbasitJohn Data AnalystIka AnasherviHaeranierina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiabzBAMBANG ARIFINasdAndriAhlan RezkiAgus Setyaadnan111' or . = '-Select-yanragaTris Retno AryaniTris R ATestingDemoAppTesting123Testing Karyawan Baru scTestDev1TestAccountPM1test uat2Test UAT test nama lengkapTest Karyawan BaruSUHERMAN RIYANTOSanti Dwi Astuti123RonaldoRatnaRamdanProject Managet TestProject Manager PrimaMikala FazaMika AnasMentari muliaMentari muliaMentari muliaLovensia Zukruff AlbasitJohn Data AnalystIka AnasherviHaeranierina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiabzBAMBANG ARIFINasdAndriAhlan RezkiAgus Setyaadnan111')]</value>
      <webElementGuid>974d8b62-efe4-46f1-ba10-ad674a625532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
